### PR TITLE
Calculation (and simple display) of remaining XP on items

### PR DESCRIPTION
**Pull request by matthubb**
Has to add all the talentgridDefs back in. Also adds progression defs. I don't know if this memory load will cause problems on some platforms.

Trying to work out the XP at which a node completes is difficult. It seems there's some information missing from the talentGrid def.

I think I've managed to calculate total XP required to max an item. There are a few items where I have more currentXP at fully maxed than my calculated max, but the difference isn't an increment of any of the numbers in the progressionDef for the item. I've no idea what's going on in these cases, so I'm screening negative XP remaining results.

Unexpected bonus, it seems to work for SubClasses too.

Display of these values would probably want to be on a toggle.
image

### CODE REVIEW

**Comment by matthubb** [comment]
I've annotated itemObject with lookups of talentGridHash and progressionHash... and just thinking about it now, I've not made them fail-safe if there's more missing data like 4th horseman.

**Comment by matthubb** [comment]
So thinking about it.. I don't expect the code quality is probably good enough for a merge into master

**Comment by dasilva333** [comment]
Also I'm on a binge trying to optimize the loading time on all platforms and just make it speedier. As of 2.0.9 windows-phone took 60+ seconds.to load the items I've managed to reduce it to 37 seconds as of 2.1.0 but that's still 30 seconds too long. So expect this pull later rather than later and I'll be profiling the before/after load times when I do pull it to make sure windows-phone doesn't freak out.

One more thing I would do if you do manage to figure out the calculations is change it from a weird long number to a percentage of (current/max) and make the top white label fill up a colored bar (the colored bar is width: (current/max)%)

Thanks!

**Comment by dasilva333** [comment]
@matthubb any updates on the problems you were facing with the data?

**Comment by matthubb** [comment]
Posted on the official forum for the API, no weekend response so far. 

The weird big numbers are, as far as I can tell, the actual XP remaining.

As far as performance and keeping the memory footprint down, it may be an idea to deference the talent and progression data and annotate the item defs.

**Comment by dasilva333** [comment]
@matthubb hey I checked out your code and ran it, there is indeed some issues remaining and I couldn't figure out the source of the issue. I created my own branch with your changes here:

https://github.com/dasilva333/TowerGhostForDestiny/tree/progress-bar

I changed the big # to a % of the maxProgress and made the width of the bar bound to that % value. Before even starting to consider committing this to the main branch we'll have to change update_definitions to preprocess some of the heavy work you're doing in processItem so expect that change to be in place too. Thanks for your help man

**Comment by matthubb** [comment]
Agreed. Hopefully there'll be some clarity on the API forum.

I'd probably like to have the big numbers, perhaps there'll be a settings pane at some point with a bunch of toggles.

**Comment by dasilva333** [comment]
@matthubb any progress or updates on the changes? no hurry take your time want to make sure it comes out good +1:

**Comment by matthubb** [comment]
Still researching the anomalous current XP items that are larger than the calculated max

**Comment by matthubb** [comment]
I'm still researching this. I have two formula for the max progression on an item. 

Applying the first finds 18 of 141 items in my inventory with off results. 

Applying the second finds 11 of 141 with off results. 

[I've posted on the API forum](https://www.bungie.net/en-GB/Forum/Post/119980070/0/0) detailing my findings and asking relevant questions.

**Comment by rkingsla** [comment]
Just as a simple comment - I have a Gjallahorn that for some reason always reports that it is not fully upgraded. It simply doesn't seem to know that it's a 365 weapon. What's more odd - I have two others that are just fine.  Certainly this is an oddity in the API?  I can only guess (because I don't recall when they were acquired) the one that shows it still isn't complete is pre-HoW, the other two post? Certainly, raising max values might play a part - from 331 to 365?  Don't know.  Like I said, it's odd.  If it means anything - unsure.

**Comment by rkingsla** [comment]
Oh, and should mention - I love this feature and would be more than happy to create a separate repo to test it.  VS makes it pretty easy, and Chrome makes it simple to test different loads.

**Pull request closed without merging**
