### PR TITLE
New icon, and docs

### PR DESCRIPTION
**Pull request by bluetidepro**
I updated the icon, I think this design will work a bit better at different sizes.

I also cleaned up some of the docs, and created a few new ones. I think this will help future contributing even better! :)

Let me know your 2 cents.

### CODE REVIEW

**Comment by bluetidepro** [comment]
@dasilva333 Cool! I'll play around with it :+1: :)

**Comment by bluetidepro** [comment]
I'll also add in those other sizes you need for the apps! :)

**Comment by bluetidepro** [comment]
@dasilva333 http://bluetide.pro/11rnU/H68jrItP - What do you think of those. The top two have the chest/keyhole, and the bottom two have just the keyhole. The right top and right bottom are just some color variations. I would suggest maybe simplifying the brand of the extension like that to have more of a basic color palette. Maybe more something like what I did using the legendary/exotic colors.

Do you want me to use one of those? If so, I can generate all the various sizes and update the PR.

Thanks! :)

**Comment by dasilva333** [comment]
You're right about simplifying I think the last one is the best one but without the purple color, use the other color you used for the other ones and I think that would be perfect. thanks man

**Comment by bluetidepro** [comment]
@dasilva333 For what it's worth, I think the bottom set are a bit better. They scale better, too, when the icon will be used smaller.

**Comment by dasilva333** [comment]
Yeah I think so too, just to clarify I do like want yellow border on fourth one. Thanks!

**Comment by bluetidepro** [comment]
I think that is all of them that you need, @dasilva333. And here is the 1024x1024: 
1024x1024

Let me know if this is good to go! :)

**Comment by dasilva333** [comment]
Really nice work man thanks a lot, expect to see the changes in 2.4.1 and above

**Pull request merged**
