### PR TITLE
Change Vault Width on special conditions

### PR DESCRIPTION
**Pull request by mistral13**
Change Vault Width to 100% if Number of Columns =3 and Vault Columns isn't 4 and Vault Position is Last. This improve the usability on mobile devices.

### CODE REVIEW

**Comment by dasilva333** [comment]
Can you provide some screenshost of what this is supposed to look like before and after the change? I'm having trouble visualizing the changes. Thanks!

**Comment by mistral13** [comment]
No Problem.

Settings:
setttings

Char view:
char

Original Vault view:
vault_original

New Vault view
vault_new

**Comment by dasilva333** [comment]
Oh that's pretty cool! I agree with that thanks for the changes

**Comment by mistral13** [comment]
Hi
Why did you limit the change to LG? 
The main reasen for my pull was the output on Mobile/iPhone (sm, md) in landscape mode.

**Comment by dasilva333** [comment]
Thanks for your input, when I rewrote it I figured the code could be simplified by checking the LG column based on the screen shots provided, in mobile/phones the (sm/md) is indeed what is active when set to landscape, I'll revisit my changes and your changes and see how I can use vaultColumns again to make this work for all tiers. Thanks!

**Comment by dasilva333** [comment]
Alright I've got a fix and an explanation as to how I feel about this whole change, so your when you made those changes it read in the form of;
'if the user has 3 characters (3+vault) and the vault is set to the right and the # of columns for the vault is not 3'
I don't agree with that fundamentally because I think a user should still have the freedom to have the vault in the right,
with any custom number of columns without being affected by this change. In essence this change should only affect those users
who would set the sm/md/lg column to 3 because only then it would create this unique scenario that you would have a vault on the second line.

So the next iteration and fix for this will be from this:
if ((self.vaultPos() == 4) && (self.lgColumn() == 8)) {

to this:
if ((self.vaultPos() == 4) && (self.lgColumn() == 8 || self.mdColumn() == 8 || self.smColumn() == 8)) {

Let me know if that works for you too, thanks!

**Comment by mistral13** [comment]
Yes it works for me

**Pull request merged**
