### PR TITLE
Materials To Upgrade

### PR DESCRIPTION
**Pull request by matthubb**
- Added the detailed item information Bungie end point to `bungie.js`.
- Added a function to `Item.js` to access this endpoint.
- Added a WIP function `update_materials` to `Item.js` which will console log the current material requirements.

### CODE REVIEW

**Comment by dasilva333** [comment]
Looks good just a few things

- There's no endpoint in the sql content to retrieve the data locally?
- Can you include the UI changes along with the back end changes all in one go?
- Can you update your code so I can automatically merge the pull request?

Thanks man so good so far

**Comment by bluetidepro** [comment]
@dasilva333 @matthubb What's the UI changes this also houses? We can always hook up the UI after? Is this the thing we wanted to prototype out a lil before we put it in?

**Comment by matthubb** [comment]
I can make a new PR which will auto merge shortly. 

Submitting this as an enabler should anyone else want to get started on the UI and the transfer logic. 

Didn't want to keep sitting on this if someone else had more UI time. 

You happy to take it as just an enabler for the feature?

**Comment by matthubb** [comment]
Closing this PR as would not auto-merge.

**Comment by matthubb** [comment]
@dasilva333

Re: mobileWorldContent

Some, but not all of the information required to know current material requirements is available in the talentDefs and the item info from the inventory endpoint. 

Specifically, there is no way to know which planetary material has been selected for an item without using this item-instance endpoint. 

Also, it provides easier access to detailed talent grid node information.

**Comment by dasilva333** [comment]
Alright cool the PR looks good I'll integrate it into master, are you going to be working on the UI for this too after?

**Comment by matthubb** [comment]
I've honestly no idea how to use knockout or bootstrap. If anyone else is
inclined to get going on UI, I'd not be offended.

If not, ill get there eventually

**Pull request closed without merging**
