### PR TITLE
small display changes and more lang updates

### PR DESCRIPTION
**Pull request by Korben85**

### CODE REVIEW

**Comment by dasilva333** [comment]
I can't accept your changes until it's fixed up, please test your code before submitting a Pull Request to avoid these mistakes, last time you made a change to the character-container-template that broke the styles please take careful consideration not to change existing elements and nesting such as adding or removing span tags. The problem in the current pull request is in the character-container-template and how you removed the existing span tags and moved the text binding to the anchor tag, that effectively overwrites the italics tag and removes the icons from the menu. Thanks for your help and contributions nontheless

**Comment by Korben85** [comment]
I reverted the changes with the span. So this commit only has some more translations.
As mentioned before I'll take a closer look and test everything I change before committing it next time.

**Comment by dasilva333** [comment]
Alright cool, just FYI because this is more of a knockout thing this is the problem with what you did before:
```
<span class="itemHolder" data-bind="text: app.activeText().message"><img src="example.jpg"></span>
```
In the example above the image will never be shown because the tag will be overwritten with the text in the data-bind parameter, so the only solution is to write something like this:
```
<span class="itemHolder"><span data-bind="text: app.activeText().message"></span><img src="example.jpg"></span>
```

**Comment by dasilva333** [comment]
@Korben85 upon further review there was also another problem where you /DELETED/ the loadouts_close key in favor of a new key called close_msg however you failed to appropriately update all the templates currently using loadouts_close, please make sure these types of mistakes/problems do not continue in the future as they are really hard to catch during a review.

**Pull request merged**
